### ISSUE TITLE
Project Feedback!

### ISSUE THREAD

**Issue by codepathreview** [PrabeshPP/Wordle#1]
Thanks for submitting your project. It looks like either the **GIF is missing** for this project, or it is **not rendering (animating)** properly. It could be that the GIF you linked expired or got deleted. 

The GIF helps us to make sure we don't miss any of the user stories you implemented. Consider the GIF a **full demo** of your app and be sure to showcase each feature you worked on!

Please record a new GIF showing all of the **user features** you completed. Otherwise, your assignment is **incomplete**.

**To record your GIF:**
To record your GIF, you can install a free tool on your computer.  We recommend:
- [Kap](https://getkap.co/) for 🍏 macOS
- [ScreenToGif](https://www.screentogif.com/) for 🪟 Windows
- [peek](https://github.com/phw/peek) for 🤖 Linux

**To render your GIF:**
Once you have uploaded your GIF to a site like [Imgur](http://imgur.com/), you can render it using the following syntax:

```markdown
<img src="https://i.imgur.com/MYGIFID.gif", width=250 />
```

If you cannot record a GIF of your app, you may record it using your mobile phone and upload the recording to your GitHub repository.   Our grader team can grade your assignment using the recording you uploaded. 

Once done, please **resubmit your work** using the submit button in the course portal **within 48-hours from the posted deadline**. If you fail to submit it within 48 hours from the posted deadline, we cannot regrade it anymore and your score will not be updated.

**NOTE:** Resubmissions to correct a missing GIF do **not** count towards towards your allotted late submissions, so long as the **only** thing you modify after the deadline is the README.  If you also update your code, it will be considered a **late submission**.

If you have any questions, please let us know by sending an email to support@codepath.org.

**Comment by PrabeshPP** [comment]
@codepathreview  I have resolved the issue. Thank you for the feedback!
